name: Publish Package

on:
  release:
    types: [published]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read
  id-token: write # npm --provenance

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Use node@20
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 20.19.0
          cache: npm
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Style
        run: |
          npm run prettier:check
          npm run lint:check

      - name: Test
        run: npm test

      - name: Publish
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
