name: Publish Package

on:
  release:
    types: [published]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read
  id-token: write # npm --provenance

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Use node@20
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20.19.0
          cache: npm
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Style
        run: |
          npm run prettier:check
          npm run lint:check

      - name: Test
        run: npm test

      - name: Publish
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
